### ISSUE TITLE
Show hashrate dynamics

### ISSUE THREAD

**Issue by polarker** [alephium/explorer#27]

**Comment by nop33** [comment]
Before agreeing on a library, we need to agree on what we want 😃 

1. We currently want to provide to the community an easy-to-understand chart of the current and historic hashrate.
2. In the future, we want to add more charts.

Inspired by [Etherscan.io](https://etherscan.io/chart/hashrate) and [blockchain.com](https://www.blockchain.com/charts/hash-rate), the first point can be achieved using a **line chart**.

Questions:
- Do we want to allow people to "select" an area of the chart and "zoom in", like on Etherscan.io?
- Do we want to allow people to export the chart in PDF/PNG/JPEG/SVG, like on Etherscan.io and blockchain.com?
- Do we want to allow people to export the data in JSON/CSV, like on Etherscan.io and blockchain.com?
- Do we want to allow people to select to view the data of the last [30 days|60 days|180 days|1 year|3 years|All Time], like on blockchain.com?
- Do we want to display a linear scale or also a logarithmic one, like on blockchain.com?
- What other charts can we foresee that we will use in the future? (so that we find a library to support them all)
   - [Total supply](https://etherscan.io/stat/supply) pie chart?
   - Other charts: https://etherscan.io/charts
- What other blockchain explorers can we get inspired from?

We first need to answer the above questions (feel free to add more), and only then agree on a frontend library. If we chose a library without having a clear idea of the features that we want, we risk wasting time in case we need to switch libraries after implementation has started...

**Comment by nop33** [comment]
Let's continue the discussion.

We can draw inspiration from (didn't find any other interesting explorers of [POW](https://coinmarketcap.com/view/pow/) projects):
- https://etherscan.io/chart/hashrate
- https://www.blockchain.com/charts/hash-rate
- https://blockchair.com/bitcoin/charts/hashrate
- https://minerstat.com/coin/ETH

My comments after reviewing Etherescan.io and Blockchain.com:
1. Both show **daily average** hashrate. Do we want to display more frequent than that? I doubt it. In that case, exporting a file from Prometheus/Grafana once a day and feeding it into the explorer would be sufficient.
2. Both allow to "zoom in/out", either by selecting a custom area of the chart or by clicking on predefined buttons to see the latest periods (30|60|180 days, 1|3 years, All time). Is that a useful feature for our explorer users, or should we stick to a static "All time" chart for now?
3. Both allow exporting the data in CSV and image.

**Comment by nop33** [comment]
Some feedback here would be welcomed :)

**Comment by mvaivre** [comment]
Let's move the discussion to #32 as the points above could concern many kind of data - not only the hashrate. 
[There.](https://github.com/alephium/explorer/issues/32#issuecomment-1011885076)
