### ISSUE TITLE
Investigate graphs librairies

### ISSUE THREAD

**Issue by mvaivre** [alephium/explorer#44]
Choose the best graph & plots library according to the kind of static and real-time data we aim to display.

**Comment by mvaivre** [comment]
Many explorers (and coinmarketcap) are using Highcharts:

```
+ Interactive (pan, zoom)
+ Crypto users are used to it
+ Feature rich
- Not open source
- Not free
```

Let's discuss, but I'd rather go for an open source library. I came across some interesting ones:

- [Visx](https://airbnb.io/visx), from AirBnB. Low level (need to write quite a lot of code), but really flexible. Based on D3.js. Allow for [interactive charting with pan and zoom](https://airbnb.io/visx/brush). Our imagination is the limit.
- [Victory](https://formidable.com/open-source/victory/), from Formidable labs. Less flexible than Visx, but much less boilerplate. Also allow for [interactive charts](https://formidable.com/open-source/victory/guides/brush-and-zoom).
- [Nivo](https://nivo.rocks/). Quite popular, but charts seem rather static. [There's an issue](https://github.com/plouc/nivo/issues/31) for adding easy interaction support, but the team is not responding.

**Comment by nop33** [comment]
- [react-chartjs-2](https://www.npmjs.com/package/react-chartjs-2) looks like an interesting choice because it is basically React components for [chart.js](https://www.npmjs.com/package/chart.js). Both of these libraries have 0 dependencies. Not sure however if it is "too simple" of a library. Need to review while comparing with our requirements.
- [react-vis](https://github.com/uber/react-vis) (from Uber) seems quite dead

Here's an article with a comparison of the most popular ones, might be helpful: https://dev.to/keefdrive/the-top-four-react-chart-libraries-that-you-need-to-know-for-2021-2nl8

**Comment by mvaivre** [comment]
- https://apexcharts.com/

Looks really interesting, interactive, free and open source.

**Comment by nop33** [comment]
It does look quite nice!! Where did you discover it?

**Comment by mvaivre** [comment]
On the [Soonaverse](https://soonaverse.com/member/0xd76676afb32294a4031707fe2c70ec16f791ccca/activity) ;)

**Comment by lf94** [comment]
visx looks _really_ nice in terms of flexibility. It also looks quite easy to use. Charts.js though is for sure more out-of-box solution.

**Comment by nop33** [comment]
I rly like apexcharts 😇 I wonder if it fits our requirements (where are they btw?)

**Comment by nop33** [comment]
On top of my head, these are things to consider:
- File size
- DevX
- Time it takes to develop
- Alive project
- Includes features that we need to build our charts

**Comment by mvaivre** [comment]
And in term of user experience and interactivity, I'm yet to find something as clean as Apexcharts - being both free and opensource.

**Comment by lf94** [comment]
We are going with Apexcharts. It's a nice balance of opinionated and flexible for our needs. Otherwise I frickin' love the tech design of visx.
